[package]
name = "getvid"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
http = "0.2.9"
json = "0.12.4"
regex = "1.7.1"
